PayCompute/Controllers/PayController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PayCompute.Entity;
using PayCompute.Models;
using PayCompute.Services;
using RotativaCore;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace PayCompute.Controllers
{
    [Authorize(Roles = "Admin,Manager")]
    public class PayController : Controller
    {
        private decimal overTimeHours;
        private decimal contractualEarnings;
        private decimal overtimeEarnings;
        private decimal totalAmount;
        private decimal tax;
        private decimal nationalInsuranceContribution;
        private decimal totalDeductions;


        private readonly IPayComputationService _payComputationService;

        private readonly INatiomalInsuranceContributionService _natiomalInsuranceContributionService;
        private readonly ITaxService _taxService;
        private readonly IEmployeeService _employeeService;

        public PayController(IPayComputationService payComputationService, INatiomalInsuranceContributionService natiomalInsuranceContributionService, ITaxService taxService, IEmployeeService employeeService)
        {
            _payComputationService = payComputationService;
            _natiomalInsuranceContributionService = natiomalInsuranceContributionService;
            _taxService = taxService;
            _employeeService = employeeService;
        }

        public IActionResult Index()
        {
            var PayRecords = _payComputationService.GetAll().Select(paymentRecord => new PaymentRecordIndexViewModel
            {
                Id = paymentRecord.Id,
                EmployeeId = paymentRecord.EmployeeId,
                FullName = paymentRecord.FullName,
                PayDate = paymentRecord.PayDate,
                PayMonth = paymentRecord.PayMonth,
                TaxYearId = paymentRecord.TaxYearId,
                //Year=paymentRecord.TaxYear.YearOfTax,//
                Year = _payComputationService.GetTaxYearById(paymentRecord.TaxYearId).YearOfTax,
                TotalEarnings = paymentRecord.TotalEarnings,
                TotalDeduction = paymentRecord.TotalDeduction,
                NetPayment = paymentRecord.NetPayment

            });


            return View(PayRecords);
        }




        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            ViewBag.EmployeeList = _employeeService.GetAllEmployeesForPayRoll(); // DropDownList => map EmployeeId
            ViewBag.TaxYears = _payComputationService.GetAllTaxYear(); // DropDownList  => map  TaxYearId
            var model = new PaymentRecordCreateViewModel();
            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(PaymentRecordCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var paymentRecord = new PaymentRecord()
                {
                    Id = model.Id,
                    EmployeeId = model.EmployeeId,
                    FullName = _employeeService.GetById(model.EmployeeId).FullName, // 
                    NINO = _employeeService.GetById(model.EmployeeId).NationalInsuranceNo,
                    PayDate = model.PayDate,
                    PayMonth = model.PayMonth,
                    TaxYearId = model.TaxYearId,
                    TaxCode = model.TaxCode,
                    HourlyRate = model.HourlyRate,
                    HourlyWorked = model.HourlyWorked,
                    ContractualHours = model.ContractualHours,
                    OverTimeHours = overTimeHours = _payComputationService.OverTimeHours(model.HourlyWorked, model.ContractualHours),// this called multiple assignment expression
                    ContractualEarnings = contractualEarnings = _payComputationService.ContractualEarnings(model.ContractualHours, model.HourlyWorked, model.HourlyRate),//multiple assignment expression
                    OverTimeEarnings = overtimeEarnings = _payComputationService.OverTimeEarnings(_payComputationService.OverTimeRate(model.HourlyRate), overTimeHours),////////multiple assignment expression

                    TotalEarnings = totalAmount = _payComputationService.TotalEarnings(overtimeEarnings, contractualEarnings),///////multiple assignment expression

                    Tax = tax = _taxService.TaxAmount(totalAmount),//multiple assignment expression

                  

                    NIC = nationalInsuranceContribution = _natiomalInsuranceContributionService.NIContribution(totalAmount),//multiple assignment expression


                    TotalDeduction = totalDeductions = _payComputationService.TotalDeduction(tax, nationalInsuranceContribution),

                    NetPayment = _payComputationService.NetPay(totalAmount, totalDeductions),





                };

                await _payComputationService.CreatAsync(paymentRecord);
                return RedirectToAction(nameof(Index));

            }


            ViewBag.EmployeeList = _employeeService.GetAllEmployeesForPayRoll(); // DropDownList => map EmployeeId
            ViewBag.TaxYears = _payComputationService.GetAllTaxYear(); // DropDownList  => map  TaxYearId
            return View(model);


        }


        [HttpGet]

        public IActionResult Detail(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var payrecord = _payComputationService.GetById(id);
            if (payrecord == null)
                return NotFound();
            var model = new PaymentRecordDetailViewModel()
            {
                Id = payrecord.Id,
                EmployeeId = payrecord.EmployeeId,
                FullName = payrecord.FullName,
                NINO = payrecord.NINO,
                PayDate = payrecord.PayDate,
                PayMonth = payrecord.PayMonth,
                TaxYearId = payrecord.TaxYearId,
                Year = _payComputationService.GetTaxYearById(payrecord.TaxYearId).YearOfTax,//
                TaxCode = payrecord.TaxCode,
                HourlyRate = payrecord.HourlyRate,
                HourlyWorked = payrecord.HourlyWorked,
                ContractualHours = payrecord.ContractualHours,
                OverTimeHours = payrecord.OverTimeHours,
                OverTimeRate = _payComputationService.OverTimeRate(payrecord.HourlyRate),//
                ContractualEarnings = payrecord.ContractualEarnings,
                OverTimeEarnings = payrecord.OverTimeEarnings,
                Tax = payrecord.Tax,
                NIC = payrecord.NIC,
           
                TotalEarnings = payrecord.TotalEarnings,
                TotalDeduction = payrecord.TotalDeduction,
                NetPayment = payrecord.NetPayment
            };


            return View(model);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult Payslip(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var payrecord = _payComputationService.GetById(id);
            if (payrecord == null)
                return NotFound();
            var model = new PaymentRecordDetailViewModel()
            {
                Id = payrecord.Id,
                EmployeeId = payrecord.EmployeeId,
                FullName = payrecord.FullName,
                NINO = payrecord.NINO,
                PayDate = payrecord.PayDate,
                PayMonth = payrecord.PayMonth,
                TaxYearId = payrecord.TaxYearId,
                Year = _payComputationService.GetTaxYearById(payrecord.TaxYearId).YearOfTax,//
                TaxCode = payrecord.TaxCode,
                HourlyRate = payrecord.HourlyRate,
                HourlyWorked = payrecord.HourlyWorked,
                ContractualHours = payrecord.ContractualHours,
                OverTimeHours = payrecord.OverTimeHours,
                OverTimeRate = _payComputationService.OverTimeRate(payrecord.HourlyRate),//
                ContractualEarnings = payrecord.ContractualEarnings,
                OverTimeEarnings = payrecord.OverTimeEarnings,
                Tax = payrecord.Tax,
                NIC = payrecord.NIC,
            
                TotalEarnings = payrecord.TotalEarnings,
                TotalDeduction = payrecord.TotalDeduction,
                NetPayment = payrecord.NetPayment
            };


            return View(model);
        }



        public IActionResult GeneratePdf(int? id )
        {
            var PayGeneratePdf = new ActionAsPdf("Payslip", new  { id = id })
            {
                FileName ="Pay.Pdf"
            };

            return PayGeneratePdf;
        }


   

    }
}

PayCompute/Views/Pay/Create.cshtml
@model PaymentRecordCreateViewModel

@{
    ViewData["Title"] = "New Pay";
}

<div class="col-md-12 grid-margin stretch-card ">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"> <a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"> <a asp-controller="Pay" asp-action="Index">PayRoll List</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> New Payment </li>
                </ol>

            </nav><br /><br />

            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="EmployeeId"></label>
                    <select asp-for="EmployeeId" asp-items="@ViewBag.EmployeeList" class="form-control">
                        <option selected disabled>---Select Employee--</option>
                        <span asp-validation-for="EmployeeId" class="text-danger"></span>
                    </select>
                </div><br /><br /><br />
                <div class="form-row">
                    <div class="form-group col-md-1">
                        <label asp-for="PayMonth"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="PayMonth" class="form-control">
                            <option selected disabled>--Select Month</option>
                            <option> January </option>
                            <option> Fabruary  </option>
                            <option> March  </option>
                            <option> April  </option>
                            <option> May  </option>
                            <option> June  </option>
                            <option> July  </option>
                            <option> August  </option>
                            <option>September </option>
                            <option>October </option>
                            <option>November </option>
                            <option>December </option>
                        </select>
                        <span asp-validation-for="PayMonth" class="text-danger"></span>

                    </div>



                    <div class="form-group col-md-1">
                        <label asp-for="TaxYearId"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="TaxYearId" asp-items="ViewBag.TaxYears" class="form-control">
                            <option selected disabled>---Select Tax Year--</option>
                           
                        </select>
                        <span asp-validation-for="TaxYearId" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-1">
                        <label asp-for="PayDate"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="PayDate" class="form-control" />
                        <span asp-validation-for="PayDate"></span>
                    </div>

                </div>

                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="HourlyRate"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyRate" class="form-control"  placeholder="0.000"/>
                        <span asp-validation-for="HourlyRate"></span>
                    </div>


                    <div class="form-group col-md-1">
                        <label asp-for="HourlyWorked"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyWorked" class="form-control" placeholder="0.000" />
                        <span asp-validation-for="HourlyWorked"></span>
                    </div>


                    <div class="form-group col-md-1">
                        <label asp-for="ContractualHours"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="ContractualHours" class="form-control"  />
                        <span asp-validation-for="ContractualHours"></span>
                    </div>
                    
                </div>
                <br /><br /><br />




                <div class="form-group ">

                    <button class="btn btn-rounded btn-primary float-left" type="submit"> <i class="fas fa-calculator" style="margin-right:5px"></i> Create </button>
                    <a asp-controller="Pay" asp-action="Index" class="btn btn-rounded btn-primary float-right">
                        <i class="fas fa-caret-square-left" style="margin-right:5px"></i> Back To Pay List
                    </a>
                    <br /><br /><br />

                </div>






            </form>

        </div>

    </div>

</div>





@section Scripts{


    @*   @{
        <partial name="_ValidationScriptsPartial" />
    }*@

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }



}

PayCompute/Views/Pay/Detail.cshtml
@model PaymentRecordDetailViewModel


@{

    ViewData["Title"] = "Payment Detail";

}

<div class="col-md-12 grid-margin stretch-card ">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"> <a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"> <a asp-controller="Pay" asp-action="Index">PayRoll List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">  Payment Detail :@Model.FullName  </li>
                </ol>

            </nav><br /><br />

            <form>

                <div class="form-row">
                    <div class="form-group col-md-1 font-weight-bold">
                        <label asp-for="FullName"></label>

                    </div>
                    <div class="form-group col-md-4 font-weight-border font-italic">
                        <input asp-for="FullName" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-2">
                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="NINO"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="NINO" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div><br /><br />
                <h3>Date And Houts</h3>
                <hr style="background-color:crimson" />
                <div class="form-row">
                    <div class="form-group col-md-1 ">
                        <label asp-for="PayMonth"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="PayMonth" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="Year"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="Year" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="PayDate"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="PayDate" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-1 ">
                        <label asp-for="HourlyRate"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyRate" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="HourlyWorked"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyWorked" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="ContractualHours"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="ContractualHours" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>


                <div class="form-row">
                    <div class=" col-md-4 ">
                    </div>

                    <div class="form-group col-md-1 ">
                        <label asp-for="OverTimeRate"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="OverTimeRate" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="OverTimeHours"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="OverTimeHours" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>
                <br />
                <h3>Deductions</h3>
                <hr style="background-color:crimson" />
                <div class="form-row">
                    <div class="form-group col-md-1 ">
                        <label asp-for="TaxCode"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="TaxCode" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="Tax"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="Tax" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="NIC"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="NIC" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>
        @*        <div class="form-row">
                    <div class="form-group col-md-4 ">
                    </div>

                    <div class="form-group col-md-1 ">
                        <label asp-for="SLC"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="SLC" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="UnionFee"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="UnionFee" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>*@

                <div class="form-row">
                    <div class="form-group col-md-8 ">
                    </div>

                    <div class="form-group col-md-1 font-weight-bold ">
                        <label asp-for="TotalDeduction"></label>

                    </div>
                    <div class="form-group col-md-3 font-weight-bolder">
                        <input asp-for="TotalDeduction" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>
                <br />
                <h3>Earnings</h3>
                <hr style="background-color:crimson" />

                <div class="form-row">
                    <div class="form-group col-md-1 ">
                        <label asp-for="ContractualEarnings"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="ContractualEarnings" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 ">
                        <label asp-for="OverTimeEarnings"></label>

                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="OverTimeEarnings" class="form-control" readonly style="background-color:#293043" />

                    </div>
                    <div class="form-group col-md-1 font-weight-bold">
                        <label asp-for="TotalEarnings"></label>

                    </div>
                    <div class="form-group col-md-3 font-weight-bolder">
                        <input asp-for="TotalEarnings" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div>


                <div class="form-row">
                    <div class="form-group col-md-8 ">
                    </div>

                    <div class="form-group col-md-1 font-weight-bold ">
                        <label asp-for="NetPayment"></label>

                    </div>
                    <div class="form-group col-md-3 font-weight-bolder">
                        <input asp-for="NetPayment" class="form-control" readonly style="background-color:#293043" />

                    </div>
                </div><br /><br /><br />


            </form>

        </div>

    </div>

</div>
<br />
<br />
<br />

PayCompute/Views/Pay/Index.cshtml
@model IEnumerable<PaymentRecordIndexViewModel>

@{
    ViewBag.Title = "Payment Records";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Payroll List</li>
                    </ol>
                </nav><br /><br />
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <a class="btn btn-xs btn-outline-success float-md-right" asp-action="Create"> New Pay</a>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>Pay Date</th>
                                    <th>Month</th>
                                    <th>Tax Year</th>
                                    <th>Total Earnings</th>
                                    <th>Total Deductions</th>
                                    <th>Net Pay</th>
                                    <th class="text-warning">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a asp-action="Detail" asp-route-id="@item.Id">
                                                @item.FullName
                                            </a>
                                        </td>
                                        <td>
                                            @item.PayDate.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>@item.PayMonth</td>
                                        <td>@item.Year</td>
                                        <td>@item.TotalEarnings.ToString("C")</td>
                                        <td>@item.TotalDeduction.ToString("c")</td>
                                        <td>@item.NetPayment.ToString("C")</td>
                                        <td>

                                            <a class="text-success" asp-action="Payslip" asp-route-id="@item.Id">
                                                <i class="fas fa-bars"></i> Preview 
                                            </a>
                                            <a class="text-danger"  asp-action="GeneratePdf" asp-route-id="@item.Id">
                                                <i class="fas fa-file-pdf " style="margin-right:3px"></i>  PayPdf
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table><br />

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PayCompute/Views/Pay/Payslip.cshtml
@model PaymentRecordDetailViewModel

@{
    ViewData["Title"] = "Pay";
}


@{
    Layout = null;
}


<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />


<div class="row">
    <div class="col-md-12 grid-margin">

        <div class="card">

            <div class="card-body">
                <div class="container-fluid d-flex justify-content-between ">
                    <div class="col-md-3 pl-0">
                        <p class="mt-5 mb-2"><b> khOrg</b></p>
                        <p> zagzig <br /> Sharkia<br /> </p>
                    </div>
                    <div class="col-md-3 pr-0">
                        <p class="mt-5 mb-2 text-right"><b> Pay Date: @Model.PayDate.ToString("dd/MM/yyyy") </b></p>
                        <p class="text-right"> Tax Code : @Model.TaxCode <br /> Year :@Model.Year<br /> </p>
                    </div>
                </div>
                <br /><br />

                <div class="col-md-12 row">
                    <div class="col-md-8">
                        <h5>Emplyee Name : @Model.FullName </h5>
                    </div>
                    <div class="col-md-8">
                        <h5>National Insurance Number: @Model.NINO </h5>
                    </div>

                </div>


            </div>

            <div class="row">
                <div class="col-md-12 table-responsive-md">
                    <table class="table table-striped">
                        <thead class="tabel-dark">
                            <tr>
                                <th>Earnings</th>
                                <th>Hours</th>

                                <th>Rates</th>

                                <th>Amount</th>
                                <th>Deductions</th>
                                <th>Amount</th>


                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><b>Basic :</b></td>
                                <td>@Model.ContractualHours.ToString("f")</td>
                                <td>@Model.HourlyRate.ToString("f")</td>
                                <td>@Model.ContractualEarnings.ToString("c")</td>
                                <td><b>Tax :</b></td>
                                <td>@Model.Tax.ToString("c")</td>

                            </tr>
                            <tr>
                                <td><b>OverTime :</b></td>
                                <td>@Model.OverTimeHours.ToString("f")</td>
                                <td>@Model.OverTimeRate.ToString("f")</td>
                                <td>@Model.OverTimeEarnings.ToString("c")</td>
                                <td><b>NIC :</b></td>
                                <td>@Model.NIC.ToString("c")</td>

                            </tr>
                          @*  <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><b>Union :</b></td>
                                <td>@Model.UnionFee.Value.ToString("c")</td>

                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><b>SLC :</b></td>
                                <td>@Model.SLC.Value.ToString("c")</td>

                            </tr>*@
                            <tr>
                                <td><b>TOTAL :</b></td>
                                <td>@Model.HourlyWorked</td>
                                <td></td>
                                <td>@Model.TotalEarnings.ToString("c")</td>
                                <td><b></b></td>
                                <td>@Model.TotalDeduction.ToString("c")</td>

                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="table-dark" ><b>Net Pay :</b></td>
                                <td class="table-dark">@Model.NetPayment.ToString("c")</td>

                            </tr>
                        </tfoot>


                    </table>
                </div>
            </div>


        </div>
    </div>


</div>
<br>
<br />
<br />